version: "3.8"

services:
  simple-rest-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: simple-rest-app:v1
    environment:
      - GIN_MODE=release
    ports:
      - "8010:8010"
    networks:
      - simple-app-net

networks:
  simple-app-net:
    name: simple-net-local
    driver: "bridge"
